
 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/mcq-app:latest', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/mcq-app:latest']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'mcq-app'
   - '--image'
   - 'gcr.io/$PROJECT_ID/mcq-app:latest'
   - '--region'
   - 'us-central1'
   - '--set-env-vars' 
   - 'API_TOKEN=$_API_TOKEN'
   - '--allow-unauthenticated'
 images:
 - 'gcr.io/$PROJECT_ID/mcq-app:latest'
 timeout: 30m